#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-WormBase
version:      0.001
version_from: WormBase.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
